"""remove_redundant_columns_from_daily_readings

Revision ID: 18554cc2928a
Revises: 987af9f22d15
Create Date: 2026-03-08 18:28:43.387115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18554cc2928a'
down_revision: Union[str, Sequence[str], None] = '987af9f22d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_readings', 'sample_bottle_label')
    op.drop_column('daily_readings', 'bucket_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_readings', sa.Column('bucket_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('daily_readings', sa.Column('sample_bottle_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
