"""Add needs_ph_update to DailyReading

Revision ID: 35b43f5bdddd
Revises: 18554cc2928a
Create Date: 2026-03-15 14:16:08.796683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b43f5bdddd'
down_revision: Union[str, Sequence[str], None] = '18554cc2928a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_readings', sa.Column('needs_ph_update', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_readings', 'needs_ph_update')
    # ### end Alembic commands ###
