"""add_ph_is_estimated_to_daily_reading_with_server_default

Revision ID: 987af9f22d15
Revises: 29c0e5b501ab
Create Date: 2026-03-08 16:43:17.451223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987af9f22d15'
down_revision: Union[str, Sequence[str], None] = '29c0e5b501ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_readings', sa.Column('ph_is_estimated', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_readings', 'ph_is_estimated')
    # ### end Alembic commands ###
