"""Phase 1 Redesign: Normalized Tables

Revision ID: bd93c569c699
Revises: 
Create Date: 2026-01-04 00:18:59.839068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd93c569c699'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_truth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('n_actual', sa.Float(), nullable=True),
    sa.Column('p_actual', sa.Float(), nullable=True),
    sa.Column('k_actual', sa.Float(), nullable=True),
    sa.Column('lab_report_ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ground_truth_device_id'), 'ground_truth', ['device_id'], unique=False)
    op.create_index(op.f('ix_ground_truth_id'), 'ground_truth', ['id'], unique=False)
    op.create_index(op.f('ix_ground_truth_timestamp'), 'ground_truth', ['timestamp'], unique=False)
    op.create_table('image_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_data_device_id'), 'image_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_image_data_id'), 'image_data', ['id'], unique=False)
    op.create_index(op.f('ix_image_data_timestamp'), 'image_data', ['timestamp'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_device_id'), 'sensor_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_id'), 'sensor_data', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_data_timestamp'), 'sensor_data', ['timestamp'], unique=False)
    op.create_table('npk_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('n_ppm', sa.Float(), nullable=True),
    sa.Column('p_ppm', sa.Float(), nullable=True),
    sa.Column('k_ppm', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npk_predictions_id'), 'npk_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_npk_predictions_timestamp'), 'npk_predictions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npk_predictions_timestamp'), table_name='npk_predictions')
    op.drop_index(op.f('ix_npk_predictions_id'), table_name='npk_predictions')
    op.drop_table('npk_predictions')
    op.drop_index(op.f('ix_sensor_data_timestamp'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_device_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_image_data_timestamp'), table_name='image_data')
    op.drop_index(op.f('ix_image_data_id'), table_name='image_data')
    op.drop_index(op.f('ix_image_data_device_id'), table_name='image_data')
    op.drop_table('image_data')
    op.drop_index(op.f('ix_ground_truth_timestamp'), table_name='ground_truth')
    op.drop_index(op.f('ix_ground_truth_id'), table_name='ground_truth')
    op.drop_index(op.f('ix_ground_truth_device_id'), table_name='ground_truth')
    op.drop_table('ground_truth')
    # ### end Alembic commands ###
