"""Add bucket_label to daily_readings

Revision ID: d250f48e4958
Revises: defb36a6bb18
Create Date: 2026-03-02 22:40:17.649595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd250f48e4958'
down_revision: Union[str, Sequence[str], None] = 'defb36a6bb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_readings', sa.Column('bucket_label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_readings', 'bucket_label')
    # ### end Alembic commands ###
