"""Add status column to DailyReading

Revision ID: defb36a6bb18
Revises: e0f0841de9be
Create Date: 2026-03-01 13:10:24.250525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defb36a6bb18'
down_revision: Union[str, Sequence[str], None] = 'e0f0841de9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_readings', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_readings', 'status')
    # ### end Alembic commands ###
