"""Phase 2 Redesign: Production Schema

Revision ID: e0f0841de9be
Revises: 
Create Date: 2026-01-04 02:37:23.315113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f0841de9be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_label', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_bottle_label', sa.String(length=50), nullable=True),
    sa.Column('n_val', sa.Float(), nullable=True),
    sa.Column('p_val', sa.Float(), nullable=True),
    sa.Column('k_val', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_index(op.f('ix_lab_results_sample_bottle_label'), 'lab_results', ['sample_bottle_label'], unique=True)
    op.create_table('daily_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('water_temp', sa.Float(), nullable=True),
    sa.Column('sample_bottle_label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_readings_id'), 'daily_readings', ['id'], unique=False)
    op.create_table('npk_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_reading_id', sa.Integer(), nullable=True),
    sa.Column('predicted_n', sa.Float(), nullable=True),
    sa.Column('predicted_p', sa.Float(), nullable=True),
    sa.Column('predicted_k', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['daily_reading_id'], ['daily_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npk_predictions_id'), 'npk_predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npk_predictions_id'), table_name='npk_predictions')
    op.drop_table('npk_predictions')
    op.drop_index(op.f('ix_daily_readings_id'), table_name='daily_readings')
    op.drop_table('daily_readings')
    op.drop_index(op.f('ix_lab_results_sample_bottle_label'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
