"""Add classification and anomaly to NPKPrediction

Revision ID: 0a1cc32e74c0
Revises: bd7945a85f23
Create Date: 2026-05-19 23:55:27.159844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1cc32e74c0'
down_revision: Union[str, Sequence[str], None] = 'bd7945a85f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npk_predictions', sa.Column('predicted_class', sa.String(), nullable=True))
    op.add_column('npk_predictions', sa.Column('is_anomaly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npk_predictions', 'is_anomaly')
    op.drop_column('npk_predictions', 'predicted_class')
    # ### end Alembic commands ###
