"""add tank_id and scaling columns for dashboard

Revision ID: 276fc0e8b333
Revises: 3dd5634096fb
Create Date: 2026-05-17 18:22:57.605421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276fc0e8b333'
down_revision: Union[str, Sequence[str], None] = '3dd5634096fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleaned_daily_readings', sa.Column('tank_id', sa.Integer(), nullable=True))
    op.add_column('npk_predictions', sa.Column('macro_scale', sa.Float(), nullable=True))
    op.add_column('npk_predictions', sa.Column('micro_scale', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npk_predictions', 'micro_scale')
    op.drop_column('npk_predictions', 'macro_scale')
    op.drop_column('cleaned_daily_readings', 'tank_id')
    # ### end Alembic commands ###
