"""add upload_interval_seconds to tank_configs

Revision ID: 2bab022e71ce
Revises: 96ef2d84006a
Create Date: 2026-05-20 22:04:48.518431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bab022e71ce'
down_revision: Union[str, Sequence[str], None] = '96ef2d84006a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tank_configs', sa.Column('upload_interval_seconds', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tank_configs', 'upload_interval_seconds')
    # ### end Alembic commands ###
