"""remove status column from daily readings

Revision ID: 333f2ec26283
Revises: 5e24c0dfa74c
Create Date: 2026-06-12 19:25:19.733094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333f2ec26283'
down_revision: Union[str, Sequence[str], None] = '5e24c0dfa74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_readings', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_readings', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
