"""add tank_configs table

Revision ID: 363f983bf2eb
Revises: bf50a4b88ac6
Create Date: 2026-05-17 01:22:43.835409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363f983bf2eb'
down_revision: Union[str, Sequence[str], None] = 'bf50a4b88ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tank_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_name', sa.String(length=50), nullable=False),
    sa.Column('water_volume_liters', sa.Float(), nullable=False),
    sa.Column('macro_brand_name', sa.String(length=100), nullable=True),
    sa.Column('macro_n_pct', sa.Float(), nullable=False),
    sa.Column('macro_p_pct', sa.Float(), nullable=False),
    sa.Column('macro_k_pct', sa.Float(), nullable=False),
    sa.Column('micro_brand_name', sa.String(length=100), nullable=True),
    sa.Column('micro_n_pct', sa.Float(), nullable=False),
    sa.Column('micro_p_pct', sa.Float(), nullable=False),
    sa.Column('micro_k_pct', sa.Float(), nullable=False),
    sa.Column('target_macro_dosage_mll', sa.Float(), nullable=False),
    sa.Column('target_micro_dosage_mll', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tank_configs_id'), 'tank_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tank_configs_id'), table_name='tank_configs')
    op.drop_table('tank_configs')
    # ### end Alembic commands ###
