"""remove daily_readings table and standardize on cleaned_daily_readings

Revision ID: 3dd5634096fb
Revises: ddc9b53d409d
Create Date: 2026-05-17 16:57:35.048393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dd5634096fb'
down_revision: Union[str, Sequence[str], None] = 'ddc9b53d409d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_daily_readings_id'), table_name='daily_readings')
    # op.drop_table('daily_readings')
    op.alter_column('npk_predictions', 'daily_reading_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # op.drop_constraint(op.f('npk_predictions_daily_reading_id_fkey'), 'npk_predictions', type_='foreignkey')
    op.create_foreign_key(None, 'npk_predictions', 'cleaned_daily_readings', ['daily_reading_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'npk_predictions', type_='foreignkey')
    op.create_foreign_key(op.f('npk_predictions_daily_reading_id_fkey'), 'npk_predictions', 'daily_readings', ['daily_reading_id'], ['id'])
    op.alter_column('npk_predictions', 'daily_reading_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('daily_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('daily_readings_experiment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_readings_pkey'))
    )
    op.create_index(op.f('ix_daily_readings_id'), 'daily_readings', ['id'], unique=False)
    # ### end Alembic commands ###
