"""add image_crop_progress table

Revision ID: 443ab99acfee
Revises: c8e26dc5c5cb
Create Date: 2026-05-16 18:53:31.642719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443ab99acfee'
down_revision: Union[str, Sequence[str], None] = 'c8e26dc5c5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_crop_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additional_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_crop_progress_id'), 'image_crop_progress', ['id'], unique=False)
    op.create_index(op.f('ix_image_crop_progress_rel_path'), 'image_crop_progress', ['rel_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_crop_progress_rel_path'), table_name='image_crop_progress')
    op.drop_index(op.f('ix_image_crop_progress_id'), table_name='image_crop_progress')
    op.drop_table('image_crop_progress')
    # ### end Alembic commands ###
