"""add cleaned_daily_readings table

Revision ID: 7d662f58fde4
Revises: 2d6d57a0472a
Create Date: 2026-05-16 18:01:09.051757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d662f58fde4'
down_revision: Union[str, Sequence[str], None] = '2d6d57a0472a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaned_daily_readings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('water_temp', sa.Float(), nullable=True),
    sa.Column('experiment_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cleaned_exp_id', 'cleaned_daily_readings', ['experiment_id'], unique=False)
    op.create_index('idx_cleaned_timestamp', 'cleaned_daily_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cleaned_timestamp', table_name='cleaned_daily_readings')
    op.drop_index('idx_cleaned_exp_id', table_name='cleaned_daily_readings')
    op.drop_table('cleaned_daily_readings')
    # ### end Alembic commands ###
