"""add sensor calibration table

Revision ID: 96ef2d84006a
Revises: 0a1cc32e74c0
Create Date: 2026-05-20 01:56:29.507474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ef2d84006a'
down_revision: Union[str, Sequence[str], None] = '0a1cc32e74c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=100), nullable=True),
    sa.Column('is_calibrating', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_calibrations_id'), 'sensor_calibrations', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_calibrations_sensor_name'), 'sensor_calibrations', ['sensor_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_calibrations_sensor_name'), table_name='sensor_calibrations')
    op.drop_index(op.f('ix_sensor_calibrations_id'), table_name='sensor_calibrations')
    op.drop_table('sensor_calibrations')
    # ### end Alembic commands ###
