"""add live telemetry table

Revision ID: 9d77603241a6
Revises: 333f2ec26283
Create Date: 2026-06-16 17:22:08.117428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d77603241a6'
down_revision: Union[str, Sequence[str], None] = '333f2ec26283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_telemetries',
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('water_temp', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tank_id'], ['tank_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tank_id')
    )
    op.create_index(op.f('ix_live_telemetries_tank_id'), 'live_telemetries', ['tank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_telemetries_tank_id'), table_name='live_telemetries')
    op.drop_table('live_telemetries')
    # ### end Alembic commands ###
