"""add_fertilizer_density_fields

Revision ID: b77d6b0a5dbb
Revises: 2bab022e71ce
Create Date: 2026-05-26 19:00:25.768947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77d6b0a5dbb'
down_revision: Union[str, Sequence[str], None] = '2bab022e71ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tank_configs', sa.Column('macro_density', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('tank_configs', sa.Column('micro_density', sa.Float(), server_default='1.0', nullable=False))
    op.create_check_constraint('macro_density_positive', 'tank_configs', 'macro_density > 0')
    op.create_check_constraint('micro_density_positive', 'tank_configs', 'micro_density > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('micro_density_positive', 'tank_configs')
    op.drop_constraint('macro_density_positive', 'tank_configs')
    op.drop_column('tank_configs', 'micro_density')
    op.drop_column('tank_configs', 'macro_density')
    # ### end Alembic commands ###
