"""add automated_action_logs table

Revision ID: bf50a4b88ac6
Revises: 443ab99acfee
Create Date: 2026-05-16 18:58:33.407151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf50a4b88ac6'
down_revision: Union[str, Sequence[str], None] = '443ab99acfee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automated_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('current_path', sa.String(length=500), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automated_action_logs_id'), 'automated_action_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automated_action_logs_id'), table_name='automated_action_logs')
    op.drop_table('automated_action_logs')
    # ### end Alembic commands ###
