"""change image_crops fk to cleaned_daily_readings

Revision ID: c8e26dc5c5cb
Revises: 6f03ac66c0d0
Create Date: 2026-05-16 18:21:23.291499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e26dc5c5cb'
down_revision: Union[str, Sequence[str], None] = '6f03ac66c0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_crops', 'daily_reading_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('image_crops_daily_reading_id_fkey'), 'image_crops', type_='foreignkey')
    op.create_foreign_key(None, 'image_crops', 'cleaned_daily_readings', ['daily_reading_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_crops', type_='foreignkey')
    op.create_foreign_key(op.f('image_crops_daily_reading_id_fkey'), 'image_crops', 'daily_readings', ['daily_reading_id'], ['id'])
    op.alter_column('image_crops', 'daily_reading_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
