"""add is_new_data column to cleaned_daily_readings

Revision ID: ddc9b53d409d
Revises: 363f983bf2eb
Create Date: 2026-05-17 15:57:33.651011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc9b53d409d'
down_revision: Union[str, Sequence[str], None] = '363f983bf2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleaned_daily_readings', sa.Column('is_new_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cleaned_daily_readings', 'is_new_data')
    # ### end Alembic commands ###
