"""add image_crops table

Revision ID: ffcee63d4b0e
Revises: 37f8f3aa201b
Create Date: 2026-05-16 18:14:47.699635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcee63d4b0e'
down_revision: Union[str, Sequence[str], None] = '37f8f3aa201b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_reading_id', sa.Integer(), nullable=True),
    sa.Column('crop_path', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('crop_type', sa.String(length=50), server_default='grid', nullable=True),
    sa.ForeignKeyConstraint(['daily_reading_id'], ['daily_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_crops_id'), 'image_crops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_crops_id'), table_name='image_crops')
    op.drop_table('image_crops')
    # ### end Alembic commands ###
